### ISSUE TITLE
Header misplaced after scrolling down and turning off screen

### ISSUE THREAD

**Issue by JasonAndujar** [ManuelPeinado/FadingActionBar#21] opened 2013-12-02 23:53 UTC
Great library, I'm loving it, but one thing has caught my attention. When scrolling down an activity, if you happen to turn off your screen and then scroll back up, the header image gets misplaced. 

Scroll down some and turn off screen..
![2013-12-02-18-48-10](https://f.cloud.github.com/assets/6090389/1659842/caf66438-5bac-11e3-8e76-d4e67c2f902f.png)

Scroll back up and you will see this :(
![2013-12-02-18-48-43](https://f.cloud.github.com/assets/6090389/1659841/c8caf278-5bac-11e3-838f-ddc537ba465c.png)

**Comment by ghost** [comment] 2013-12-18 12:02
Was this fixed in version 3.0.0 (2013-12-04)?

**Comment by ManuelPeinado** [comment] 2013-12-23 17:39
Hi. I cannot reproduce this issue with my Nexus 4. What device / version of Android are you using? Thanks in advance.

**Comment by JasonAndujar** [comment] 2013-12-30 19:47
I am no longer having this issue, thanks

**Closed as completed** 2014-01-19 10:05 UTC
